import { type Prizes } from "../models/prizer";

export const prizers: Prizes[] = [
  {
    id: 1,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar um ",
    prize: "KIT CONJUNTO TALHERES 25PC PRETO/VERMELHO",
    confetti: true,
    repeat: false,
    display: "Kit Talheres",
    color: "#E41E25",
  },
  {
    id: 2,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar um ",
    prize: "CESTO TELADO 60L (ROUPEIRO)",
    confetti: true,
    repeat: false,
    display: "Cesto Roupa",
    color: "#EBE742",
  },
  {
    id: 3,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar um ",
    prize: "KIT POTE COZINHA C/02 UND",
    confetti: true,
    repeat: false,
    display: "Kit Potes",
    color: "#E41E25",
  },
  {
    id: 4,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar uma ",
    prize: "BANQUETA (preta)",
    confetti: true,
    repeat: false,
    display: "Banqueta",
    color: "#EBE742",
  },
  {
    id: 5,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar um ",
    prize: "PORTA CERVEJA PLASTLIMA (plástico personalizado)",
    confetti: true,
    repeat: false,
    display: "Porta Cerveja",
    color: "#E41E25",
  },
  {
    id: 6,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar um ",
    prize: "SQUEEZE 600ML",
    confetti: true,
    repeat: false,
    display: "Squeeze",
    color: "#EBE742",
  },
  {
    id: 7,
    title: "Que pena!",
    message: "Infelizmente não foi dessa vez!",
    prize: "",
    confetti: false,
    repeat: false,
    display: "Tente Novamente",
    color: "#F37D3E",
  },
];
