import { type Prizes } from "../models/prizer";

export const prizers: Prizes[] = [
  {
    id: 1,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar um ",
    prize: "15% de DESCONTO",
    confetti: true,
    repeat: false,
    display: "DESCONTO 15%",
    color: "#1BA2B5",
  },
    {
    id: 2,
    title: "Que pena ",
    message: "Você acaba de ",
    prize: "passar a vez",
    confetti: false,
    repeat: false,
    display: "PASSA A VEZ",
    color: "#1d747f",
  },
  {
    id: 3,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar um ",
    prize: "15% de DESCONTO",
    confetti: true,
    repeat: false,
    display: "DESCONTO 15%",
    color: "#59868c",
  },
    {
    id: 4,
    title: "Que pena ",
    message: "Você acaba de ",
    prize: "passar a vez",
    confetti: false,
    repeat: false,
    display: "PASSA A VEZ",
    color: "#1d747f",
  },
  {
    id: 5,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar um ",
    prize: "15% de DESCONTO",
    confetti: true,
    repeat: false,
    display: "DESCONTO 15%",
    color: "#1BA2B5",
  },
    {
    id: 6,
    title: "Que pena ",
    message: "Você acaba de ",
    prize: "passar a vez",
    confetti: false,
    repeat: false,
    display: "PASSA A VEZ",
    color: "#1d747f",
  },
  {
    id: 7,
    title: "Parabéns 🎉🎉",
    message: "Você acaba de ganhar um ",
    prize: "15% de DESCONTO",
    confetti: true,
    repeat: false,
    display: "DESCONTO 15%",
    color: "#59868c",
  },
  {
    id: 8,
    title: "Que pena ",
    message: "Você acaba de ",
    prize: "passar a vez",
    confetti: false,
    repeat: false,
    display: "PASSA A VEZ",
    color: "#1d747f",
  },
];
